theme = "plain"
icons = "awesome"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]

#[[block]]
#block = "watson"
#show_time = true
#state_path = "/home/kacper/.config/watson/state"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

